### ISSUE TITLE
License inconsistencies

### ISSUE THREAD

**Issue by radifar** [guyuehuo/opendock#1]
I found that the license stored in the parent directory of the repository, in setup configuration, and the documentation are all different. In the `LICENSE` file it is MIT, in the `setup.py` and `conf.py` it is GPL 3.0 and yet in the [documentation](https://opendock-readthedocs.readthedocs.io/en/latest/index.html) it is stated that the license is Apache license. I think they need to be synced to prevent further confusion.

Thank you,
Radif

**Comment by guyuehuo** [comment]
Thank you for your feedback. This issue was caused by an oversight on our part. All LICENSE files have now been standardized to MIT. Best wishes.
